Repository Delta-Icons/android, pull requests merged in 2023-02, with the labels that each got.

#578 Fix MarineTraffic icon link
  app/src/main/assets/appfilter.xml
  app/src/main/res/xml/appfilter.xml
Labels: compinfos

#579 Add 2 icons
  app/src/main/assets/appfilter.xml
  app/src/main/assets/drawable.xml
  app/src/main/res/drawable-nodpi/alkitab.png
  app/src/main/res/drawable-nodpi/m-pesa.png
  app/src/main/res/xml/appfilter.xml
  app/src/main/res/xml/drawable.xml
  contributed-vectors/alkitab.svg
  contributed-vectors/m-pesa.svg
Labels: icons

#580 FOSS fixes
  app/src/foss/java/website/leifs/delta/applications/CandyBar.java
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-nodpi/m_pesa.png
  app/src/play/AndroidManifest.xml
Labels: misc

#581 add icons
  app/src/main/assets/appfilter.xml
  app/src/main/assets/drawable.xml
  app/src/main/res/drawable-nodpi/ad_free.png
  app/src/main/res/drawable-nodpi/anpaside.png
  app/src/main/res/drawable-nodpi/burpy_walls.png
  app/src/main/res/drawable-nodpi/comviq.png
  app/src/main/res/drawable-nodpi/direct_express.png
  app/src/main/res/drawable-nodpi/disposable_camera.png
  app/src/main/res/drawable-nodpi/dooz.png
  app/src/main/res/drawable-nodpi/foreground.png
  app/src/main/res/drawable-nodpi/gridle.png
  app/src/main/res/drawable-nodpi/mintos.png
  app/src/main/res/drawable-nodpi/nova_video_player.png
  app/src/main/res/drawable-nodpi/permission_manager_x.png
  app/src/main/res/drawable-nodpi/qserv.png
  app/src/main/res/drawable-nodpi/secuso_minesweeper.png
  app/src/main/res/drawable-nodpi/tag_livros.png
  app/src/main/res/drawable-nodpi/xplora.png
  app/src/main/res/xml/appfilter.xml
  app/src/main/res/xml/drawable.xml
  contributed-vectors/ad_free.svg
  contributed-vectors/anpaside.svg
  contributed-vectors/burpy_walls.svg
  contributed-vectors/comviq.svg
  contributed-vectors/direct_express.svg
  contributed-vectors/disposable_camera.svg
  contributed-vectors/dooz.svg
  contributed-vectors/foreground.svg
  contributed-vectors/gridle.svg
  contributed-vectors/mintos.svg
  contributed-vectors/nova_video_player.svg
  contributed-vectors/permission_manager_x.svg
  contributed-vectors/qserv.svg
  contributed-vectors/secuso_minesweeper.svg
  contributed-vectors/tag_livros.svg
  contributed-vectors/xplora.svg
  requests.txt
Labels: icons

#582 Fix Avion Rewards
  app/src/main/assets/appfilter.xml
  app/src/main/res/xml/appfilter.xml
Labels: compinfos

#583 Add ScoreSquash icon
  app/src/main/assets/appfilter.xml
  app/src/main/assets/drawable.xml
  app/src/main/res/drawable-nodpi/scoresquash.png
  app/src/main/res/xml/appfilter.xml
  app/src/main/res/xml/drawable.xml
  contributed-vectors/scoresquash.svg
Labels: icons, compinfos

#585 feat: new icons
  app/src/main/assets/appfilter.xml
  app/src/main/assets/drawable.xml
  app/src/main/res/drawable-nodpi/easy_xkcd.png
  app/src/main/res/drawable-nodpi/forgetmenot.png
  app/src/main/res/drawable-nodpi/private_location.png
  app/src/main/res/drawable-nodpi/sai_fdroid.png
  app/src/main/res/xml/appfilter.xml
  app/src/main/res/xml/drawable.xml
  resources/vectors/easy_xkcd.svg
  resources/vectors/forgetmenot.svg
  resources/vectors/private_location.svg
  resources/vectors/sai_fdroid.svg
Labels: icons, compinfos

#586 add componentinfo
  app/src/main/assets/appfilter.xml
  app/src/main/res/xml/appfilter.xml
Labels: compinfos

#589 add icons
  app/src/main/assets/appfilter.xml
  app/src/main/assets/drawable.xml
  app/src/main/res/drawable-nodpi/_8bitdo.png
  app/src/main/res/drawable-nodpi/image_resizer.png
  app/src/main/res/drawable-nodpi/intesis_ac_cloud.png
  app/src/main/res/drawable-nodpi/jojoy.png
  app/src/main/res/drawable-nodpi/mastercard.png
  app/src/main/res/drawable-nodpi/meitu.png
  app/src/main/res/drawable-nodpi/scee.png
  app/src/main/res/drawable-nodpi/t_mobile_money.png
  app/src/main/res/drawable-nodpi/unofficial_acnh_guide.png
  app/src/main/res/drawable-nodpi/vivo_themes.png
  app/src/main/res/xml/appfilter.xml
  app/src/main/res/xml/drawable.xml
  resources/requests.txt
  resources/vectors/_8bitdo.svg
  resources/vectors/image_resizer.svg
  resources/vectors/intesis_ac_cloud.svg
  resources/vectors/jojoy.svg
  resources/vectors/mastercard.svg
  resources/vectors/meitu.svg
  resources/vectors/scee.svg
  resources/vectors/t_mobile_money.svg
  resources/vectors/unofficial_acnh_guide.svg
  resources/vectors/vivo_themes.svg
Labels: icons, compinfos

#591 add icons and compinfo
  app/src/main/assets/appfilter.xml
  app/src/main/assets/drawable.xml
  app/src/main/res/drawable-nodpi/etesync.png
  app/src/main/res/drawable-nodpi/john_gba.png
  app/src/main/res/drawable-nodpi/octohide_vpn.png
  app/src/main/res/drawable-nodpi/scandit_barcode_scanner.png
  app/src/main/res/drawable-nodpi/screenshot_recorder.png
  app/src/main/res/xml/appfilter.xml
  app/src/main/res/xml/drawable.xml
  resources/requests.txt
  resources/vectors/etesync.svg
  resources/vectors/john_gba.svg
  resources/vectors/octohide_vpn.svg
  resources/vectors/scandit_barcode_scanner.svg
  resources/vectors/screenshot_recorder.svg
Labels: icons, compinfos

#593 add icons
  resources/new_icons.yaml
  resources/utilities/icons/c_sharp_shell_net_ide.png
  resources/utilities/icons/c_sharp_shell_net_ide.svg
  resources/utilities/icons/diamond_bus.png
  resources/utilities/icons/diamond_bus.svg
  resources/utilities/icons/free_reunion_visual_voicemail.png
  resources/utilities/icons/free_reunion_visual_voicemail.svg
  resources/utilities/icons/kakao_webtoon.png
  resources/utilities/icons/kakao_webtoon.svg
  resources/utilities/icons/metamorfosis.png
  resources/utilities/icons/metamorfosis.svg
  resources/utilities/icons/momup.png
  resources/utilities/icons/momup.svg
  resources/utilities/icons/scruff.png
  resources/utilities/icons/scruff.svg
Labels: icons, compinfos

#595 add icons and compinfo, sort appfilter
  app/src/main/assets/appfilter.xml
  app/src/main/res/drawable-nodpi/mrepo.png
  app/src/main/res/xml/appfilter.xml
  resources/new_icons.yaml
  resources/requests.txt
  resources/utilities/icons/air_math.png
  resources/utilities/icons/air_math.svg
  resources/utilities/icons/audio_widget_pack.png
  resources/utilities/icons/audio_widget_pack.svg
  resources/utilities/icons/desaturate_pro_kwgt.png
  resources/utilities/icons/desaturate_pro_kwgt.svg
  resources/utilities/icons/droidvim.png
  resources/utilities/icons/droidvim.svg
  resources/utilities/icons/finamp.png
  resources/utilities/icons/finamp.svg
  resources/utilities/icons/freecbt.png
  resources/utilities/icons/freecbt.svg
  resources/utilities/icons/gainsfire.png
  resources/utilities/icons/gainsfire.svg
  resources/utilities/icons/giropay.png
  resources/utilities/icons/giropay.svg
  resources/utilities/icons/gloom.png
  resources/utilities/icons/gloom.svg
  resources/utilities/icons/luminous_black_poweramp_skin.png
  resources/utilities/icons/luminous_black_poweramp_skin.svg
  resources/utilities/icons/medilog.png
  resources/utilities/icons/medilog.svg
  resources/utilities/icons/ourocard.png
  resources/utilities/icons/ourocard.svg
  resources/utilities/icons/pbz_mobile.png
  resources/utilities/icons/pbz_mobile.svg
  resources/utilities/icons/right_dialer.png
  resources/utilities/icons/right_dialer.svg
  resources/utilities/icons/runday.png
  resources/utilities/icons/runday.svg
  resources/utilities/icons/scuderia_ferrari.png
  resources/utilities/icons/scuderia_ferrari.svg
  resources/utilities/icons/super_productivity.png
  resources/utilities/icons/super_productivity.svg
  resources/utilities/icons/tawakkalna.png
  resources/utilities/icons/tawakkalna.svg
  resources/utilities/icons/volkskrant.png
  resources/utilities/icons/volkskrant.svg
  resources/utilities/icons/wawa.png
  resources/utilities/icons/wawa.svg
  resources/utilities/icons/whisker.png
  resources/utilities/icons/whisker.svg
  resources/utilities/icons/yuito.png
  resources/utilities/icons/yuito.svg
  resources/vectors/mrepo.svg
Labels: icons, compinfos

#596 Phrasing and grammar
  app/src/main/res/values/dashboard_configurations.xml
  app/src/main/res/values/dashboard_faqs.xml
Labels: misc

#597 Add 1 icon, update components
  app/src/main/assets/appfilter.xml
  app/src/main/assets/drawable.xml
  app/src/main/res/drawable-nodpi/applist_detector.png
  app/src/main/res/xml/appfilter.xml
  app/src/main/res/xml/drawable.xml
  resources/vectors/applist_detector.svg
Labels: icons, compinfos

#598 add icons
  resources/new_icons.yaml
  resources/utilities/icons/assistive_touch_menu.png
  resources/utilities/icons/assistive_touch_menu.svg
  resources/utilities/icons/autenticacao_gov.png
  resources/utilities/icons/autenticacao_gov.svg
  resources/utilities/icons/boxfresh.png
  resources/utilities/icons/boxfresh.svg
  resources/utilities/icons/carga_sube.png
  resources/utilities/icons/carga_sube.svg
  resources/utilities/icons/dzienniczek_vulcan.png
  resources/utilities/icons/dzienniczek_vulcan.svg
  resources/utilities/icons/finanzguru.png
  resources/utilities/icons/finanzguru.svg
  resources/utilities/icons/haema_diary.png
  resources/utilities/icons/haema_diary.svg
  resources/utilities/icons/hail.png
  resources/utilities/icons/hail.svg
  resources/utilities/icons/myindihome.png
  resources/utilities/icons/myindihome.svg
  resources/utilities/icons/priority_pass.png
  resources/utilities/icons/priority_pass.svg
  resources/utilities/icons/smarthq.png
  resources/utilities/icons/smarthq.svg
Labels: icons, compinfos
